AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS
  Sample SAM Template for AWS

Globals:
  Function:
    Timeout: 60

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 
      Handler: 
      Runtime: java8
      MemorySize: 512
     


